package middleware

import (
	"bytes"
	"io"
	"net/http"
	"sync/atomic"
)

func NewWrapResponseWriter(rw http.ResponseWriter) *WrapResponseWriter {
	rw1, ok := rw.(*WrapResponseWriter)
	if !ok {
		return &WrapResponseWriter{ResponseWriter: rw}
	}

	return rw1
}

type WrapResponseWriter struct {
	http.ResponseWriter
	wroteHeader int32
	discard     bool
	statusCode  int
	written     int
	tee         *bytes.Buffer
}

func (rw *WrapResponseWriter) Write(b []byte) (n int, err error) {
	rw.maybeWriteHeader()
	if !rw.discard {
		n, err = rw.ResponseWriter.Write(b)
		if rw.tee != nil {
			_, err2 := rw.tee.Write(b[:n])
			// Prefer errors generated by the proxied writer.
			if err == nil {
				err = err2
			}
		}
	} else {
		n, err = io.Discard.Write(b)
	}
	rw.written += n
	return n, err
}

func (rw *WrapResponseWriter) Tee(b *bytes.Buffer) {
	rw.tee = b
}

func (rw *WrapResponseWriter) Status() int {
	return rw.statusCode
}

func (rw *WrapResponseWriter) Size() int {
	return rw.written
}

func (rw *WrapResponseWriter) Bytes() []byte {
	if rw.tee == nil {
		return nil
	}
	return rw.tee.Bytes()
}

func (rw *WrapResponseWriter) String() string {
	if rw.tee == nil {
		return ""
	}
	return rw.tee.String()
}

func (rw *WrapResponseWriter) Flush() {
	atomic.StoreInt32(&rw.wroteHeader, 1)
	flusher := rw.ResponseWriter.(http.Flusher) // nolint:forcetypeassert
	flusher.Flush()
}

func (rw *WrapResponseWriter) WriteHeader(code int) {
	if atomic.CompareAndSwapInt32(&rw.wroteHeader, 0, 1) {
		rw.statusCode = code
		if !rw.discard {
			rw.ResponseWriter.WriteHeader(code)
		}
	}
}

func (rw *WrapResponseWriter) Discard() {
	rw.discard = true
}

func (rw *WrapResponseWriter) maybeWriteHeader() {
	if atomic.CompareAndSwapInt32(&rw.wroteHeader, 0, 1) {
		rw.WriteHeader(http.StatusOK)
	}
}
